version: '3.3'
# Simple setup for dev

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
     - .:/var/cli:cached
     - $HOME/.ssh/${SSH_KEY}:/var/www/.ssh/${SSH_KEY}
     - $HOME/.platformsh:/var/www/.platformsh
    stdin_open: true
    tty: true
    network_mode: bridge
