#!/usr/bin/env php
<?php

define('CLI_ACCOUNTS_SITE', 'https://marketplace.commerceguys.com');
// Important: CLI_VERIFY_SSL_CERT must always be true in production.
define('CLI_VERIFY_SSL_CERT', true);
// __DIR__ called in a class will point to the class directory. Saved now it
// ensure there's always a path to the cli root.
define('CLI_ROOT', __DIR__);

if (file_exists(CLI_ROOT . '/vendor/autoload.php')) {
    require CLI_ROOT . '/vendor/autoload.php';
} else {
    // we are globally installed via Composer
    require CLI_ROOT . '/../../autoload.php';
}

use CommerceGuys\Platform\Cli\Application;
use CommerceGuys\Platform\Cli\Input\ArgvInput;

$input = new ArgvInput();
$application = new Application();
$application->run($input);
