#!/usr/bin/env php
<?php

define('CLI_ROOT', __DIR__);

// Ensure that errors are only reported once.
ini_set('display_errors', 1);
ini_set('log_errors', 0);

if (file_exists(CLI_ROOT . '/vendor/autoload.php')) {
    require CLI_ROOT . '/vendor/autoload.php';
} elseif (file_exists(CLI_ROOT . '/../../autoload.php')) {
    // we are globally installed via Composer
    require CLI_ROOT . '/../../autoload.php';
} else {
    echo "Composer autoload file not found.\n";
    echo "You need to run 'composer install'.\n";
    exit(1);
}

use Platformsh\Cli\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$application = new Application();
$application->run($input);
