# Test CLI configuration
application:
  name: 'Platform Test CLI'
  slug: 'platform-test-cli'
  version: '1.0.0'
  executable: 'platform-test'
  env_prefix: 'TEST_CLI_'
  user_config_dir: '.platform-test-cli'

service:
  name: 'Platform.sh Testing'
  env_prefix: 'PLATFORM_'
  project_config_dir: '.platform'
  console_url: 'https://console.cli-tests.example.com'

api:
  # Placeholder URLs which can be replaced during tests.
  base_url: 'http://127.0.0.1'
  auth_url: 'http://127.0.0.1'

  organizations: true
  centralized_permissions: true
  teams: true
  user_verification: true
  metrics: true

  vendor_filter: 'test-vendor'

ssh:
  domain_wildcards: ['*.cli-tests.example.com']

detection:
  git_remote_name: 'platform-test'
  git_domain: 'git.cli-tests.example.com'
  site_domains: ['cli-tests.example.com']
  cluster_header: 'X-Platform-Cluster'
