<?php

namespace Platformsh\Cli\SiteAlias;

use Platformsh\Client\Model\Project;

class DrushPhp extends DrushAlias
{
    /**
     * {@inheritdoc}
     */
    protected function getFilename($groupName, $drushDir)
    {
        return $drushDir . '/' . $groupName . '.aliases.drushrc.php';
    }

    /**
     * {@inheritdoc}
     */
    protected function formatAliases(array $aliases)
    {
        $formatted = [];
        foreach ($aliases as $aliasName => $newAlias) {
            $formatted[] = $this->formatAlias($newAlias, $aliasName);
        }

        return implode("\n", $formatted);
    }

    /**
     * Format a single Drush site alias as a string.
     *
     * @param string $name    The alias name (the name of the environment).
     * @param array  $alias   The alias, as an array.
     *
     * @return string
     */
    private function formatAlias(array $alias, $name)
    {
        return sprintf(
            "\$aliases['%s'] = %s;\n",
            str_replace("'", "\\'", $name),
            var_export($alias, true)
        );
    }

    /**
     * {@inheritdoc}
     */
    protected function getExistingAliases(array $filenames)
    {
        // This may create a PHP parse error for invalid syntax in the alias
        // file, but in that case the user could not run Drush anyway.
        $aliases = [];
        foreach ($filenames as $filename) {
            if (file_exists($filename)) {
                include $filename;
            }
        }

        return $aliases;
    }

    /**
     * {@inheritdoc}
     */
    protected function getHeader(Project $project)
    {
        return "<?php\n"
            . "/**\n * @file"
            . "\n * Drush aliases for the " . $this->config->get('service.name') . " project \"{$project->title}\"."
            . "\n *"
            . "\n * This file is auto-generated by the " . $this->config->get('application.name') . "."
            . "\n *"
            . "\n * WARNING"
            . "\n * This file may be regenerated at any time."
            . "\n * - User-defined aliases will be preserved."
            . "\n * - Aliases for active environments (including any custom additions) will be preserved."
            . "\n * - Aliases for deleted or inactive environments will be deleted."
            . "\n * - All other information will be deleted."
            . "\n */\n\n";
    }

    /**
     * Generate new aliases.
     *
     * @param array $apps
     * @param array $environments
     *
     * @return array
     */
    protected function generateNewAliases(array $apps, array $environments)
    {
        $aliases = [];

        foreach ($apps as $app) {
            $appId = $app->getId();

            // Generate aliases for the remote environments.
            foreach ($environments as $environment) {
                $alias = $this->generateRemoteAlias($environment, $app, !$app->isSingle());
                if (!$alias) {
                    continue;
                }

                $aliasName = $environment->id;
                if (count($apps) > 1) {
                    $aliasName .= '--' . $appId;
                }

                $aliases[$aliasName] = $alias;
            }

            // Generate an alias for the local environment.
            $localAliasName = self::LOCAL_ALIAS_NAME;
            if (count($apps) > 1) {
                $localAliasName .= '--' . $appId;
            }
            $aliases[$localAliasName] = $this->generateLocalAlias($app);
        }

        return $aliases;
    }
}
