#!/usr/bin/env sh
get_git_head() {
  if git rev-parse --verify HEAD >/dev/null 2>&1
  then
    echo "HEAD"
  else
    git hash-object -t tree /dev/null
  fi
}

against=$(get_git_head)

#@TODO: add check to see if CLI is actually installed... 

exec < /dev/tty #redirect keyboard input so we can do interactivity in symfony
$APPLICATION_EXECUTABLE commit:validate $against 1>/dev/null

if [ $? -eq 0 ]
then
  echo "CLI says OK, allow commit."
  exit 0
else
  echo "Cancelling commit."
  exit 1
fi
exec <&-