name: Security
on: [pull_request]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4

      - name: 'Scan for secrets'
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified
